pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM',
                  branches: [[name: '*/main']],
                  userRemoteConfigs: [[url: 'https://github.com/masiur047/TestCICD.git']]
                ])
            }
        }

        stage('Restore') {
            steps {
                echo "🔄 Restoring NuGet packages..."
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                echo "🛠 Building the project..."
                sh 'dotnet build --configuration Release'
            }
        }

        stage('Test') {
            steps {
                echo "✅ Running unit tests..."
                sh 'dotnet test --logger trx --results-directory TestResults'
            }
        }

        stage('Publish') {
            steps {
                echo "📦 Publishing the project..."
                sh 'dotnet publish -c Release -o publish'
            }
        }
    }

    post {
        always {
            echo "📄 Archiving test results..."
            junit 'TestResults/**/*.trx'
        }
    }
}
